# Generated by Django 4.2.19 on 2025-02-07 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_alter_ativo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ativos.fabricante'),
        ),
    ]
