# Generated by Django 4.2.19 on 2025-02-07 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ativos', '0003_alter_ativo_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departamento'),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ativos.tipoativo'),
        ),
    ]
